<a href="https://colab.research.google.com/github/tyleresong/mis433/blob/main/assignment_data_manipuation_flights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation in Pandas

In this assignment, you will be working on the same dataframe of flights departing New York City in 2013.

In [48]:
import pandas as pd

In [49]:
pip install nycflights13

Requirement already satisfied: nycflights13 in /usr/local/lib/python3.12/dist-packages (0.0.3)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from nycflights13) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->nycflights13) (1.17.0)

In [50]:
# Install the package 'nycflights13' before you can run this
from nycflights13 import flights
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,370.044053
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,374.273128
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z,408.375000
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z,516.721311
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z,394.137931

In [51]:
flights.shape

(336776, 20)

## Data frame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [52]:
# use describe() to summarize all columns
flights.describe(include='all')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
count,336776.0,336776.000000,336776.000000,328521.000000,336776.000000,328521.000000,328063.000000,336776.000000,327346.000000,336776,336776.000000,334264,336776,336776,327346.000000,336776.000000,336776.000000,336776.000000,336776,327346.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,4043,3,105,NaN,NaN,NaN,NaN,6936,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA,NaN,N725MQ,EWR,ORD,NaN,NaN,NaN,NaN,2013-09-13T12:00:00Z,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58665,NaN,575,120835,17283,NaN,NaN,NaN,NaN,94,NaN
mean,2013.0,6.548510,15.710787,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,NaN,1971.923620,NaN,NaN,NaN,150.686460,1039.912604,13.180247,26.230100,NaN,394.273655
std,0.0,3.414457,8.768607,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,NaN,1632.471938,NaN,NaN,NaN,93.688305,733.233033,4.661316,19.300846,NaN,60.633015
min,2013.0,1.000000,1.000000,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,NaN,1.000000,NaN,NaN,NaN,20.000000,17.000000,1.000000,0.000000,NaN,76.800000
25%,2013.0,4.000000,8.000000,907.000000,906.000000,-5.000000,1104.000000,1124.000000,-17.000000,NaN,553.000000,NaN,NaN,NaN,82.000000,502.000000,9.000000,8.000000,NaN,358.089172
50%,2013.0,7.000000,16.000000,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,NaN,1496.000000,NaN,NaN,NaN,129.000000,872.000000,13.000000,29.000000,NaN,404.150943
75%,2013.0,10.000000,23.000000,1744.000000,1729.000000,11.000000,1940.000000,1945.000000,14.000000,NaN,3465.000000,NaN,NaN,NaN,192.000000,1389.000000,17.000000,44.000000,NaN,438.823529
max,2013.0,12.000000,31.000000,2400.000000,2359.000000,1301.000000,2400.000000,2359.000000,1272.000000,NaN,8500.000000,NaN,NaN,NaN,695.000000,4983.000000,23.000000,59.000000,NaN,703.384615

## Question 1. Selecting rows

From the 'flights' dataframe, find all flights that satisfy the following certain conditions:

In [53]:
# Had an arrival delay of two or more hours
flights[flights.arr_delay >= 120]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
119,2013,1,1,811.0,630,101.0,1047.0,830,137.0,MQ,4576,N531MQ,LGA,CLT,118.0,544,6,30,2013-01-01T11:00:00Z,276.610169
151,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,3944,N942MQ,JFK,BWI,41.0,184,18,35,2013-01-01T23:00:00Z,269.268293
218,2013,1,1,957.0,733,144.0,1056.0,853,123.0,UA,856,N534UA,EWR,BOS,37.0,200,7,33,2013-01-01T12:00:00Z,324.324324
268,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,UA,1086,N76502,LGA,IAH,248.0,1416,9,0,2013-01-01T14:00:00Z,342.580645
447,2013,1,1,1505.0,1310,115.0,1638.0,1431,127.0,EV,4497,N17984,EWR,RIC,63.0,277,13,10,2013-01-01T18:00:00Z,263.809524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,3459,N916XJ,JFK,BNA,95.0,765,15,45,2013-09-30T19:00:00Z,483.157895
336668,2013,9,30,1951.0,1649,182.0,2157.0,1903,174.0,EV,4294,N13988,EWR,SAV,95.0,708,16,49,2013-09-30T20:00:00Z,447.157895
336724,2013,9,30,2053.0,1815,158.0,2310.0,2054,136.0,EV,5292,N600QX,EWR,ATL,91.0,746,18,15,2013-09-30T22:00:00Z,491.868132
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30T22:00:00Z,361.200000
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-10-01T00:00:00Z,460.487805

In [54]:
# Flew to Houston (IAH or HOU)
flights[(flights.dest == 'IAH') | (flights.dest == 'HOU')]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,370.044053
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,374.273128
32,2013,1,1,623.0,627,-4.0,933.0,932,1.0,UA,496,N459UA,LGA,IAH,229.0,1416,6,27,2013-01-01T11:00:00Z,371.004367
81,2013,1,1,728.0,732,-4.0,1041.0,1038,3.0,UA,473,N488UA,LGA,IAH,238.0,1416,7,32,2013-01-01T12:00:00Z,356.974790
89,2013,1,1,739.0,739,0.0,1104.0,1038,26.0,UA,1479,N37408,EWR,IAH,249.0,1400,7,39,2013-01-01T12:00:00Z,337.349398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336524,2013,9,30,1729.0,1720,9.0,2001.0,2010,-9.0,UA,652,N455UA,EWR,IAH,173.0,1400,17,20,2013-09-30T21:00:00Z,485.549133
336527,2013,9,30,1735.0,1715,20.0,2010.0,2005,5.0,WN,2067,N296WN,EWR,HOU,188.0,1411,17,15,2013-09-30T21:00:00Z,450.319149
336618,2013,9,30,1859.0,1859,0.0,2134.0,2159,-25.0,UA,1128,N14731,LGA,IAH,180.0,1416,18,59,2013-09-30T22:00:00Z,472.000000
336694,2013,9,30,2015.0,2015,0.0,2244.0,2307,-23.0,UA,1545,N17730,EWR,IAH,174.0,1400,20,15,2013-10-01T00:00:00Z,482.758621
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,475,N477UA,EWR,IAH,175.0,1400,21,6,2013-10-01T01:00:00Z,480.000000

In [55]:
# Were operated by United (UA), American (AA), or Delta (DL)
flights[(flights.carrier == 'UA') | (flights.carrier == 'AA') | (flights.carrier == 'DL') ]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,370.044053
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,374.273128
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z,408.375000
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z,394.137931
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01T10:00:00Z,287.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,475,N477UA,EWR,IAH,175.0,1400,21,6,2013-10-01T01:00:00Z,480.000000
336744,2013,9,30,2121.0,2100,21.0,2349.0,14,-25.0,DL,2363,N193DN,JFK,LAX,296.0,2475,21,0,2013-10-01T01:00:00Z,501.689189
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,185,N335AA,JFK,LAX,298.0,2475,21,40,2013-10-01T01:00:00Z,498.322148
336755,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,523,N813UA,EWR,BOS,37.0,200,21,56,2013-10-01T01:00:00Z,324.324324
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-10-01T01:00:00Z,483.962264

In [56]:
# Departed in July, August, and September
flights[(flights.month == 7) | (flights.month == 8) | (flights.month == 9)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
250450,2013,7,1,1.0,2029,212.0,236.0,2359,157.0,B6,915,N653JB,JFK,SFO,315.0,2586,20,29,2013-07-02T00:00:00Z,492.571429
250451,2013,7,1,2.0,2359,3.0,344.0,344,0.0,B6,1503,N805JB,JFK,SJU,200.0,1598,23,59,2013-07-02T03:00:00Z,479.400000
250452,2013,7,1,29.0,2245,104.0,151.0,1,110.0,B6,234,N348JB,JFK,BTV,66.0,266,22,45,2013-07-02T02:00:00Z,241.818182
250453,2013,7,1,43.0,2130,193.0,322.0,14,188.0,B6,1371,N794JB,LGA,FLL,143.0,1076,21,30,2013-07-02T01:00:00Z,451.468531
250454,2013,7,1,44.0,2150,174.0,300.0,100,120.0,AA,185,N324AA,JFK,LAX,297.0,2475,21,50,2013-07-02T01:00:00Z,500.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z,NaN
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z,NaN
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z,NaN
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z,NaN
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z,NaN

In [57]:
# Arrived more than two hours late, but didn’t leave late
flights[(flights.arr_delay > 120) & (flights.dep_delay <= 0)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
22911,2013,1,27,1419.0,1420,-1.0,1754.0,1550,124.0,MQ,3728,N1EAMQ,EWR,ORD,135.0,719,14,20,2013-01-27T19:00:00Z,319.555556
33011,2013,10,7,1350.0,1350,0.0,1736.0,1526,130.0,EV,5181,N611QX,LGA,MSN,117.0,812,13,50,2013-10-07T17:00:00Z,416.410256
33019,2013,10,7,1357.0,1359,-2.0,1858.0,1654,124.0,AA,1151,N3CMAA,LGA,DFW,192.0,1389,13,59,2013-10-07T17:00:00Z,434.062500
41075,2013,10,16,657.0,700,-3.0,1258.0,1056,122.0,B6,3,N703JB,JFK,SJU,225.0,1598,7,0,2013-10-16T11:00:00Z,426.133333
55985,2013,11,1,658.0,700,-2.0,1329.0,1015,194.0,VX,399,N629VA,JFK,LAX,336.0,2475,7,0,2013-11-01T11:00:00Z,441.964286
152766,2013,3,18,1844.0,1847,-3.0,39.0,2219,140.0,UA,389,N560UA,JFK,SFO,386.0,2586,18,47,2013-03-18T22:00:00Z,401.968912
180893,2013,4,17,1635.0,1640,-5.0,2049.0,1845,124.0,MQ,4540,N721MQ,LGA,DTW,130.0,502,16,40,2013-04-17T20:00:00Z,231.692308
181270,2013,4,18,558.0,600,-2.0,1149.0,850,179.0,AA,707,N3EXAA,LGA,DFW,234.0,1389,6,0,2013-04-18T10:00:00Z,356.153846
181327,2013,4,18,655.0,700,-5.0,1213.0,950,143.0,AA,2083,N565AA,EWR,DFW,230.0,1372,7,0,2013-04-18T11:00:00Z,357.913043
213693,2013,5,22,1827.0,1830,-3.0,2217.0,2010,127.0,MQ,4674,N518MQ,LGA,CLE,90.0,419,18,30,2013-05-22T22:00:00Z,279.333333
214512,2013,5,23,1810.0,1810,0.0,2208.0,2000,128.0,MQ,4626,N525MQ,LGA,CMH,82.0,479,18,10,2013-05-23T22:00:00Z,350.487805
226434,2013,6,5,1604.0,1615,-11.0,2041.0,1840,121.0,MQ,4657,N510MQ,LGA,ATL,158.0,762,16,15,2013-06-05T20:00:00Z,289.367089
235033,2013,6,14,1708.0,1710,-2.0,2227.0,2015,132.0,AA,181,N320AA,JFK,LAX,334.0,2475,17,10,2013-06-14T21:00:00Z,444.610778
244329,2013,6,24,1602.0,1605,-3.0,2134.0,1916,138.0,DL,706,N3768,JFK,AUS,247.0,1521,16,5,2013-06-24T20:00:00Z,369.473684
247568,2013,6,27,2052.0,2100,-8.0,13.0,2210,123.0,US,2144,N952UW,LGA,BOS,46.0,184,21,0,2013-06-28T01:00:00Z,240.000000
249957,2013,6,30,1423.0,1425,-2.0,1816.0,1554,142.0,B6,2402,N206JB,JFK,BUF,80.0,301,14,25,2013-06-30T18:00:00Z,225.750000
250689,2013,7,1,905.0,905,0.0,1443.0,1223,140.0,DL,1057,N337NB,LGA,MIA,183.0,1096,9,5,2013-07-01T13:00:00Z,359.344262
256340,2013,7,7,1659.0,1700,-1.0,2050.0,1823,147.0,US,2183,N948UW,LGA,DCA,64.0,214,17,0,2013-07-07T21:00:00Z,200.625000
256358,2013,7,7,1727.0,1730,-3.0,2203.0,1951,132.0,F9,837,N263AV,LGA,DEN,236.0,1620,17,30,2013-07-07T21:00:00Z,411.864407
256373,2013,7,7,1746.0,1755,-9.0,2133.0,1921,132.0,B6,1407,N374JB,JFK,IAD,78.0,228,17,55,2013-07-07T21:00:00Z,175.384615
256405,2013,7,7,1823.0,1830,-7.0,2201.0,1955,126.0,MQ,3486,N724MQ,LGA,BNA,113.0,764,18,30,2013-07-07T22:00:00Z,405.663717
270742,2013,7,22,1555.0,1600,-5.0,2139.0,1938,121.0,DL,141,N713TW,JFK,SFO,371.0,2586,16,0,2013-07-22T20:00:00Z,418.221024
270752,2013,7,22,1606.0,1615,-9.0,2056.0,1831,145.0,DL,1619,N970DL,LGA,MSP,140.0,1020,16,15,2013-07-22T20:00:00Z,437.142857
270762,2013,7,22,1628.0,1630,-2.0,2151.0,1939,132.0,B6,423,N625JB,JFK,LAX,332.0,2475,16,30,2013-07-22T20:00:00Z,447.289157
276564,2013,7,28,1710.0,1711,-1.0,2248.0,2039,129.0,B6,167,N510JB,JFK,OAK,353.0,2576,17,11,2013-07-28T21:00:00Z,437.847025
287148,2013,8,8,1457.0,1500,-3.0,1828.0,1624,124.0,US,2185,N746UW,LGA,DCA,70.0,214,15,0,2013-08-08T19:00:00Z,183.428571
291439,2013,8,13,657.0,659,-2.0,1015.0,814,121.0,EV,4522,N14188,EWR,BNA,146.0,748,6,59,2013-08-13T10:00:00Z,307.397260
305985,2013,8,28,1157.0,1200,-3.0,1520.0,1316,124.0,US,2179,N737US,LGA,DCA,63.0,214,12,0,2013-08-28T16:00:00Z,203.809524
325764,2013,9,19,656.0,700,-4.0,1037.0,833,124.0,UA,331,N808UA,LGA,ORD,192.0,733,7,0,2013-09-19T11:00:00Z,229.062500

In [58]:
# Were delayed by at least an hour, but made up over 30 minutes in flight
flights[(flights.dep_delay >= 60) & ((flights.sched_arr_time - flights.arr_time) > 30)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
151,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,3944,N942MQ,JFK,BWI,41.0,184,18,35,2013-01-01T23:00:00Z,269.268293
815,2013,1,1,2205.0,1720,285.0,46.0,2040,246.0,AA,1999,N5DNAA,EWR,MIA,146.0,1085,17,20,2013-01-01T22:00:00Z,445.890411
830,2013,1,1,2312.0,2000,192.0,21.0,2110,191.0,EV,4312,N13958,EWR,DCA,44.0,199,20,0,2013-01-02T01:00:00Z,271.363636
831,2013,1,1,2323.0,2200,83.0,22.0,2313,69.0,EV,4257,N13538,EWR,BTV,44.0,266,22,0,2013-01-02T03:00:00Z,362.727273
834,2013,1,1,2343.0,1724,379.0,314.0,1938,456.0,EV,4321,N21197,EWR,MCI,222.0,1092,17,24,2013-01-01T22:00:00Z,295.135135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335773,2013,9,29,2253.0,2000,173.0,121.0,2300,141.0,VX,415,N628VA,JFK,LAX,303.0,2475,20,0,2013-09-30T00:00:00Z,490.099010
335775,2013,9,29,2314.0,2140,94.0,11.0,2255,76.0,MQ,3621,N848MQ,JFK,DCA,39.0,213,21,40,2013-09-30T01:00:00Z,327.692308
335777,2013,9,29,2324.0,2100,144.0,39.0,2235,124.0,MQ,3317,N528MQ,LGA,RDU,61.0,431,21,0,2013-09-30T01:00:00Z,423.934426
335778,2013,9,29,2327.0,1942,225.0,153.0,2250,183.0,B6,1271,N659JB,LGA,FLL,129.0,1076,19,42,2013-09-29T23:00:00Z,500.465116
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-10-01T00:00:00Z,460.487805

In [59]:
# Departed between midnight and 6am (inclusive)
flights[(flights.dep_time >= 0) & (flights.dep_time <= 600)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,370.044053
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,374.273128
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z,408.375000
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z,516.721311
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z,394.137931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335802,2013,9,30,557.0,600,-3.0,852.0,923,-31.0,UA,303,N510UA,JFK,SFO,326.0,2586,6,0,2013-09-30T10:00:00Z,475.950920
335803,2013,9,30,558.0,600,-2.0,815.0,829,-14.0,EV,4137,N16981,EWR,ATL,107.0,746,6,0,2013-09-30T10:00:00Z,418.317757
335804,2013,9,30,558.0,600,-2.0,742.0,749,-7.0,DL,731,N337NB,LGA,DTW,83.0,502,6,0,2013-09-30T10:00:00Z,362.891566
335805,2013,9,30,559.0,600,-1.0,NaN,715,NaN,WN,464,N411WN,EWR,MDW,NaN,711,6,0,2013-09-30T10:00:00Z,NaN
335806,2013,9,30,600.0,600,0.0,844.0,856,-12.0,B6,601,N588JB,JFK,FLL,139.0,1069,6,0,2013-09-30T10:00:00Z,461.438849

In [60]:
# How many flights have a missing dep_time?
count = flights['dep_time'].isnull().sum()
print(count)

8255

## Question 2. Sorting

In [61]:
# Sort flights to find the least delayed flights. Find the flights that left earliest.
flights.sort_values(by=['dep_delay'])
flights.sort_values(by=['dep_time'])

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
10452,2013,1,13,1.0,2249,72.0,108.0,2357,71.0,B6,22,N206JB,JFK,SYR,41.0,209,22,49,2013-01-14T03:00:00Z,305.853659
100800,2013,12,20,1.0,2359,2.0,430.0,440,-10.0,B6,1503,N608JB,JFK,SJU,182.0,1598,23,59,2013-12-21T04:00:00Z,526.813187
212954,2013,5,22,1.0,1935,266.0,154.0,2140,254.0,EV,4361,N27200,EWR,TYS,94.0,631,19,35,2013-05-22T23:00:00Z,402.765957
297030,2013,8,19,1.0,2359,2.0,347.0,350,-3.0,B6,745,N552JB,JFK,PSE,201.0,1617,23,59,2013-08-20T03:00:00Z,482.686567
131559,2013,2,24,1.0,2245,76.0,121.0,2354,87.0,B6,608,N216JB,JFK,PWM,56.0,273,22,45,2013-02-25T03:00:00Z,292.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z,NaN
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z,NaN
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z,NaN
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z,NaN
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z,NaN

In [62]:
# Which flights travelled the farthest? Which travelled the shortest?
flights.sort_values(by=['distance'], ascending=False)
flights.sort_values(by=['distance'])

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
275945,2013,7,27,NaN,106,NaN,NaN,245,NaN,US,1632,NaN,EWR,LGA,NaN,17,1,6,2013-07-27T05:00:00Z,NaN
116412,2013,2,6,2125.0,2129,-4.0,2207.0,2224,-17.0,EV,4619,N12564,EWR,PHL,28.0,80,21,29,2013-02-07T02:00:00Z,171.428571
164109,2013,3,30,1942.0,1950,-8.0,2026.0,2044,-18.0,EV,4457,N12569,EWR,PHL,24.0,80,19,50,2013-03-30T23:00:00Z,200.000000
150994,2013,3,16,1947.0,1950,-3.0,2055.0,2044,11.0,EV,4457,N48901,EWR,PHL,31.0,80,19,50,2013-03-16T23:00:00Z,154.838710
19088,2013,1,22,2203.0,2130,33.0,2317.0,2225,52.0,EV,4619,N13538,EWR,PHL,31.0,80,21,30,2013-01-23T02:00:00Z,154.838710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246012,2013,6,26,954.0,1000,-6.0,1421.0,1435,-14.0,HA,51,N384HA,JFK,HNL,601.0,4983,10,0,2013-06-26T14:00:00Z,497.470882
5473,2013,1,7,1042.0,900,102.0,1620.0,1530,50.0,HA,51,N385HA,JFK,HNL,612.0,4983,9,0,2013-01-07T14:00:00Z,488.529412
47786,2013,10,23,952.0,1000,-8.0,1431.0,1450,-19.0,HA,51,N393HA,JFK,HNL,619.0,4983,10,0,2013-10-23T14:00:00Z,483.004847
136482,2013,3,1,904.0,900,4.0,1438.0,1540,-62.0,HA,51,N388HA,JFK,HNL,617.0,4983,9,0,2013-03-01T14:00:00Z,484.570502
111507,2013,2,1,855.0,900,-5.0,1442.0,1540,-58.0,HA,51,N388HA,JFK,HNL,620.0,4983,9,0,2013-02-01T14:00:00Z,482.225806

## Question 3. Selecting Columns

Use at least three ways to select dep_time, dep_delay, arr_time, and arr_delay from flights.

In [63]:
# Method 1
flights[['dep_time', 'dep_delay', 'arr_time', 'arr_delay']]

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [64]:
# Method 2
flights.loc[:, ['dep_time', 'dep_delay', 'arr_time', 'arr_delay']]

        dep_time  dep_delay  arr_time  arr_delay
0          517.0        2.0     830.0       11.0
1          533.0        4.0     850.0       20.0
2          542.0        2.0     923.0       33.0
3          544.0       -1.0    1004.0      -18.0
4          554.0       -6.0     812.0      -25.0
...          ...        ...       ...        ...
336771       NaN        NaN       NaN        NaN
336772       NaN        NaN       NaN        NaN
336773       NaN        NaN       NaN        NaN
336774       NaN        NaN       NaN        NaN
336775       NaN        NaN       NaN        NaN

[336776 rows x 4 columns]

In [65]:
# Method 3
flights.iloc[:, [3, 4, 5, 6]]

        dep_time  sched_dep_time  dep_delay  arr_time
0          517.0             515        2.0     830.0
1          533.0             529        4.0     850.0
2          542.0             540        2.0     923.0
3          544.0             545       -1.0    1004.0
4          554.0             600       -6.0     812.0
...          ...             ...        ...       ...
336771       NaN            1455        NaN       NaN
336772       NaN            2200        NaN       NaN
336773       NaN            1210        NaN       NaN
336774       NaN            1159        NaN       NaN
336775       NaN             840        NaN       NaN

[336776 rows x 4 columns]

## Question 4. Adding new columns

Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers.

For example, 759 means 7:59 and 801 means 8:01. Their difference is not 42 but 2 minutes.

In [66]:
# Convert them to a more convenient representation of number of minutes since
# midnight (0).
times = flights[['dep_time', 'sched_dep_time']]
minutes_since_midnight = (times['dep_time'] // 100) * 60 + (times['dep_time'] % 100)
print(minutes_since_midnight)

0         317.0
1         333.0
2         342.0
3         344.0
4         354.0
          ...
336771      NaN
336772      NaN
336773      NaN
336774      NaN
336775      NaN
Name: dep_time, Length: 336776, dtype: float64

In [67]:
# Create a new column of arr_time - dep_time.
flights.assign(arr_time = flights.arr_time - flights.dep_time)


# Compare this column with air_time.

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
0,2013,1,1,517.0,515,2.0,313.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,370.044053
1,2013,1,1,533.0,529,4.0,317.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,374.273128
2,2013,1,1,542.0,540,2.0,381.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z,408.375000
3,2013,1,1,544.0,545,-1.0,460.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z,516.721311
4,2013,1,1,554.0,600,-6.0,258.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z,394.137931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z,NaN
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z,NaN
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z,NaN
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z,NaN
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z,NaN

In [68]:
# Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
# Try creating a column to calculate dep_delay from dep_time and sched_dep_time (and/or other columns if necessary).

flights.assign(dep_delay = flights.sched_dep_time - flights.dep_time)


# Test your results.

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
0,2013,1,1,517.0,515,-2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,370.044053
1,2013,1,1,533.0,529,-4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,374.273128
2,2013,1,1,542.0,540,-2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z,408.375000
3,2013,1,1,544.0,545,1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z,516.721311
4,2013,1,1,554.0,600,46.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z,394.137931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z,NaN
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z,NaN
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z,NaN
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z,NaN
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z,NaN

## Question 5. Mixing things together

The following questions may require multiple operations above.

In [69]:
# Find the 20 most delayed flights.
# Display the following: year,month,day,carrier,flight,dep_delay,arr_delay,carrier
# How do you want to handle ties?

flights.sort_values(by=['dep_delay'], ascending=False).head(20)
flights.loc[:, ['year', 'month', 'day', 'carrier', 'flight', 'dep_delay', 'arr_delay', 'carrier']]

        year  month  day carrier  flight  dep_delay  arr_delay carrier
0       2013      1    1      UA    1545        2.0       11.0      UA
1       2013      1    1      UA    1714        4.0       20.0      UA
2       2013      1    1      AA    1141        2.0       33.0      AA
3       2013      1    1      B6     725       -1.0      -18.0      B6
4       2013      1    1      DL     461       -6.0      -25.0      DL
...      ...    ...  ...     ...     ...        ...        ...     ...
336771  2013      9   30      9E    3393        NaN        NaN      9E
336772  2013      9   30      9E    3525        NaN        NaN      9E
336773  2013      9   30      MQ    3461        NaN        NaN      MQ
336774  2013      9   30      MQ    3572        NaN        NaN      MQ
336775  2013      9   30      MQ    3531        NaN        NaN      MQ

[336776 rows x 8 columns]

In [70]:
# Sort all AA flights to find the top 10 fastest (highest speed) flights.
# Display the following: year,month,day,carrier,flight,orig,dest,distance,air_time,speed (miles per hour)
flights.speed.assign = flights.distance / (flights.air_time / 60)
flights[flights.carrier == 'AA'].sort_values(by=['speed'], ascending=False).head(10)
flights.loc[:, ['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'distance', 'air_time', 'speed']]

,year,month,day,carrier,flight,origin,dest,distance,air_time,speed
0,2013,1,1,UA,1545,EWR,IAH,1400,227.0,370.044053
1,2013,1,1,UA,1714,LGA,IAH,1416,227.0,374.273128
2,2013,1,1,AA,1141,JFK,MIA,1089,160.0,408.375000
3,2013,1,1,B6,725,JFK,BQN,1576,183.0,516.721311
4,2013,1,1,DL,461,LGA,ATL,762,116.0,394.137931
...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,9E,3393,JFK,DCA,213,NaN,NaN
336772,2013,9,30,9E,3525,LGA,SYR,198,NaN,NaN
336773,2013,9,30,MQ,3461,LGA,BNA,764,NaN,NaN
336774,2013,9,30,MQ,3572,LGA,CLE,419,NaN,NaN
336775,2013,9,30,MQ,3531,LGA,RDU,431,NaN,NaN

In [71]:
# Find all flights that satisfy the following:
# - From John F. Kennedy Airpot (JFK) or Newark Aiport (EWR) to Seattle-Tacoma Airport (SEA)
# - Carrier is UA, AA, or DL.
# - Dates from 4/1/2013 (inclusive) to 4/3/2013 (inclusive)
# - Scheduled arrival time is before noon.
# - Display the following: year,month,day,carrier,flight,origin,dest,sched_dep_time,sched_arr_time
# - Sort by year, month, day, sched_arr_time

flights[(flights.origin == 'JFK') | (flights.origin == 'EWR') & (flights.dest == 'SEA') & (flights.carrier == 'UA') | (flights.carrier == 'AA') | (flights.carrier == 'DL')]
flights[(flights.year == 2013) & (flights.month == 4) & (flights.day == 1) | (flights.day == 2) | (flights.day == 3)]
flights[(flights.arr_time > 1200)]
flights.loc[:, ['year', 'month', 'day', 'carrier', 'flight', 'origin', 'dest', 'sched_dep_time', 'sched_arr_time']]
flights.sort_values(by=['year', 'month', 'day', 'sched_arr_time'])

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,speed
774,2013,1,1,2035.0,2030,5.0,2337.0,5,-28.0,UA,1482,N38268,EWR,LAX,333.0,2454,20,30,2013-01-02T01:00:00Z,442.162162
827,2013,1,1,2306.0,2245,21.0,28.0,5,23.0,B6,30,N281JB,JFK,ROC,59.0,264,22,45,2013-01-02T03:00:00Z,268.474576
719,2013,1,1,1929.0,1920,9.0,3.0,7,-4.0,UA,1071,N27205,EWR,BQN,192.0,1585,19,20,2013-01-02T00:00:00Z,495.312500
829,2013,1,1,2310.0,2255,15.0,24.0,15,9.0,B6,112,N646JB,JFK,BUF,57.0,301,22,55,2013-01-02T03:00:00Z,316.842105
795,2013,1,1,2103.0,2110,-7.0,2345.0,17,-32.0,DL,1668,N3738B,JFK,LAS,309.0,2248,21,10,2013-01-02T02:00:00Z,436.504854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111241,2013,12,31,2039.0,2046,-7.0,7.0,2358,9.0,B6,329,N571JB,JFK,RSW,179.0,1074,20,46,2014-01-01T01:00:00Z,360.000000
111231,2013,12,31,2012.0,1900,72.0,53.0,2359,54.0,AA,1029,N5DSAA,JFK,SJU,193.0,1598,19,0,2014-01-01T00:00:00Z,496.787565
111240,2013,12,31,2037.0,2040,-3.0,2351.0,2359,-8.0,B6,523,N768JB,JFK,LAX,354.0,2475,20,40,2014-01-01T01:00:00Z,419.491525
111253,2013,12,31,2116.0,2045,31.0,34.0,2359,35.0,B6,1295,N645JB,JFK,AUS,235.0,1521,20,45,2014-01-01T01:00:00Z,388.340426
111258,2013,12,31,2122.0,2130,-8.0,2.0,2359,3.0,B6,1677,N307JB,JFK,JAX,138.0,828,21,30,2014-01-01T02:00:00Z,360.000000