<a href="https://colab.research.google.com/github/tyleresong/mis433/blob/main/assignment_IMDB_manipulation_summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - Analyzing the IMDB Top 1000 Movies

In the next few assignments, you will be working with this data set of IMDB top 1000 movies.

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [45]:
import pandas as pd
import numpy as np

To read the data file from your Google Drive, mount your drive first.

In [46]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [47]:
# Read the data file "imdb_top_1000.csv" to a dataframe named "imdb"
imdb = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Data//imdb_top_1000.csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [48]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [49]:
# List all the column names:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [50]:
# Display top 10 movies' title, released year and IMDB rating.
imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']].head(10)

                                    Series_Title Released_Year  IMDB_Rating
0                       The Shawshank Redemption          1994          9.3
1                                  The Godfather          1972          9.2
2                                The Dark Knight          2008          9.0
3                         The Godfather: Part II          1974          9.0
4                                   12 Angry Men          1957          9.0
5  The Lord of the Rings: The Return of the King          2003          8.9
6                                   Pulp Fiction          1994          8.9
7                               Schindler's List          1993          8.9
8                                      Inception          2010          8.8
9                                     Fight Club          1999          8.8

In [51]:
# Display movies ranked 11-20.
# Show their title, released year and IMDB rating.
imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']][11:21]

                                      Series_Title Released_Year  IMDB_Rating
11                                    Forrest Gump          1994          8.8
12                 Il buono, il brutto, il cattivo          1966          8.8
13           The Lord of the Rings: The Two Towers          2002          8.7
14                                      The Matrix          1999          8.7
15                                      Goodfellas          1990          8.7
16  Star Wars: Episode V - The Empire Strikes Back          1980          8.7
17                 One Flew Over the Cuckoo's Nest          1975          8.7
18                                        Hamilton          2020          8.6
19                                    Gisaengchung          2019          8.6
20                                 Soorarai Pottru          2020          8.6

In [52]:
# Select all movies directed by Quentin Tarantino.
# Show their title, released year, IMDB rating, and gross.
imdb[imdb['Director'] == 'Quentin Tarantino'][['Series_Title', 'Released_Year', 'IMDB_Rating', 'Gross']]

                         Series_Title Released_Year  IMDB_Rating        Gross
6                        Pulp Fiction          1994          8.9  107,928,762
62                   Django Unchained          2012          8.4  162,805,434
93               Inglourious Basterds          2009          8.3  120,540,719
103                    Reservoir Dogs          1992          8.3    2,832,029
241                 Kill Bill: Vol. 1          2003          8.1   70,099,045
369                 Kill Bill: Vol. 2          2004          8.0   66,208,183
584                 The Hateful Eight          2015          7.8   54,117,416
879  Once Upon a Time... in Hollywood          2019          7.6  142,502,728

In [53]:
# Select all R rated movies with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.
imdb[imdb['Certificate'] == 'R'][imdb['IMDB_Rating'] >= 8.5][['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']]

/tmp/ipykernel_10987/3422635389.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  imdb[imdb['Certificate'] == 'R'][imdb['IMDB_Rating'] >= 8.5][['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']]

           Series_Title Released_Year Certificate  IMDB_Rating
24  Saving Private Ryan          1998           R          8.6
38          The Pianist          2002           R          8.5
40   American History X          1998           R          8.5

In [54]:
# How many unique values are there in the column "Released_Year"?
# Hint: nunique()
imdb['Released_Year'].nunique()

100

In [55]:
# Count the number of movies in each "Released_Year"?
# Hint: value_counts()
imdb['Released_Year'].value_counts()

Released_Year
2014    32
2004    31
2009    29
2013    28
2016    28
        ..
1920     1
1930     1
1922     1
1943     1
PG       1
Name: count, Length: 100, dtype: int64

In [56]:
# In this dataset, there is a movie with an error in "Released_Year".
# Hint: Released_Year should be a 4-digit integer but this movie's is not.
# Find this movie.
imdb[imdb['Released_Year'] == 'PG']

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [57]:
# Correct the values for the corresponding columns ("Released_Year" and "Certificate").
# You may want to look up this movie on www.imdb.com.
# Hint: You can set value for a particular row by: df.loc[row_name, column_name] = new_value
imdb.loc[966, 'Released_Year'] = 1995
imdb.loc[966, 'Certificate'] = 'PG-13'
imdb.loc[966]

Poster_Link      https://m.media-amazon.com/images/M/MV5BNjEzYj...
Series_Title                                             Apollo 13
Released_Year                                                 1995
Certificate                                                  PG-13
Runtime                                                    140 min
Genre                                    Adventure, Drama, History
IMDB_Rating                                                    7.6
Overview         NASA must devise a strategy to return Apollo 1...
Meta_score                                                    77.0
Director                                                Ron Howard
Star1                                                    Tom Hanks
Star2                                                  Bill Paxton
Star3                                                  Kevin Bacon
Star4                                                  Gary Sinise
No_of_Votes                                                 269197
Gross                                                  173,837,933
Name: 966, dtype: object

In [58]:
# Change the data type of "Released_Year" to int
imdb['Released_Year'] = imdb['Released_Year'].astype(int)

In [59]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.
imdb[['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']][imdb['Released_Year'] >= 2010][imdb['IMDB_Rating'] >= 8.5]

/tmp/ipykernel_10987/1486645522.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  imdb[['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']][imdb['Released_Year'] >= 2010][imdb['IMDB_Rating'] >= 8.5]

        Series_Title  Released_Year Certificate  IMDB_Rating
8          Inception           2010          UA          8.8
18          Hamilton           2020       PG-13          8.6
19      Gisaengchung           2019           A          8.6
20   Soorarai Pottru           2020           U          8.6
21      Interstellar           2014          UA          8.6
33             Joker           2019           A          8.5
34          Whiplash           2014           A          8.5
35  The Intouchables           2011          UA          8.5

In [60]:
# Select all movies whose genres contain 'Animation'
imdb[imdb['Genre'].str.contains('Animation')]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
23,https://m.media-amazon.com/images/M/MV5BMjlmZm...,Sen to Chihiro no kamikakushi,2001,U,125 min,"Animation, Adventure, Family",8.6,"During her family's move to the suburbs, a sul...",96.0,Hayao Miyazaki,Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,651376,"10,055,859"
43,https://m.media-amazon.com/images/M/MV5BYTYxNG...,The Lion King,1994,U,88 min,"Animation, Adventure, Drama",8.5,Lion prince Simba and his father are targeted ...,88.0,Roger Allers,Rob Minkoff,Matthew Broderick,Jeremy Irons,James Earl Jones,942045,"422,783,777"
46,https://m.media-amazon.com/images/M/MV5BZmY2Nj...,Hotaru no haka,1988,U,89 min,"Animation, Drama, War",8.5,A young boy and his little sister struggle to ...,94.0,Isao Takahata,Tsutomu Tatsumi,Ayano Shiraishi,Akemi Yamaguchi,Yoshiko Shinohara,235231,NaN
56,https://m.media-amazon.com/images/M/MV5BODRmZD...,Kimi no na wa.,2016,U,106 min,"Animation, Drama, Fantasy",8.4,Two strangers find themselves linked in a biza...,79.0,Makoto Shinkai,Ryûnosuke Kamiki,Mone Kamishiraishi,Ryô Narita,Aoi Yûki,194838,"5,017,246"
58,https://m.media-amazon.com/images/M/MV5BMjMwND...,Spider-Man: Into the Spider-Verse,2018,U,117 min,"Animation, Action, Adventure",8.4,Teen Miles Morales becomes the Spider-Man of h...,87.0,Bob Persichetti,Peter Ramsey,Rodney Rothman,Shameik Moore,Jake Johnson,375110,"190,241,310"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,https://m.media-amazon.com/images/M/MV5BODkxNG...,Mulan,1998,U,88 min,"Animation, Adventure, Family",7.6,"To save her father from death in the army, a y...",71.0,Tony Bancroft,Barry Cook,Ming-Na Wen,Eddie Murphy,BD Wong,256906,"120,620,254"
971,https://m.media-amazon.com/images/M/MV5BMTY5Nj...,Omohide poro poro,1991,U,118 min,"Animation, Drama, Romance",7.6,A twenty-seven-year-old office worker travels ...,90.0,Isao Takahata,Miki Imai,Toshirô Yanagiba,Yoko Honna,Mayumi Izuka,27071,"453,243"
976,https://m.media-amazon.com/images/M/MV5BN2JlZT...,The Little Mermaid,1989,U,83 min,"Animation, Family, Fantasy",7.6,A mermaid princess makes a Faustian bargain in...,88.0,Ron Clements,John Musker,Jodi Benson,Samuel E. Wright,Rene Auberjonois,237696,"111,543,479"
986,https://m.media-amazon.com/images/M/MV5BMzZiOD...,Watership Down,1978,U,91 min,"Animation, Adventure, Drama",7.6,Hoping to escape destruction by human develope...,64.0,Martin Rosen,John Hubley,John Hurt,Richard Briers,Ralph Richardson,33656,NaN
992,https://m.media-amazon.com/images/M/MV5BMjAwMT...,The Jungle Book,1967,U,78 min,"Animation, Adventure, Family",7.6,Bagheera the Panther and Baloo the Bear have a...,65.0,Wolfgang Reitherman,Phil Harris,Sebastian Cabot,Louis Prima,Bruce Reitherman,166409,"141,843,612"

In [61]:
# Create a new dataframe called "stars" including the following columns:
# Series_Title, Released_Year, Star1, Star2, Star3, Star4
stars = imdb[['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']]
stars.head()

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler

In [62]:
# Create a new dataframe called "genres" including the following columns:
# Series_Title, Released_Year, Genre.
genres = imdb[['Series_Title', 'Released_Year', 'Genre']]
genres.head()

               Series_Title  Released_Year                 Genre
0  The Shawshank Redemption           1994                 Drama
1             The Godfather           1972          Crime, Drama
2           The Dark Knight           2008  Action, Crime, Drama
3    The Godfather: Part II           1974          Crime, Drama
4              12 Angry Men           1957          Crime, Drama

In [63]:
# Sorting:
# Sort dataframe genres in ascending order of "Released_Year"
genres.sort_values('Released_Year', ascending=True)

                     Series_Title  Released_Year                         Genre
321  Das Cabinet des Dr. Caligari           1920      Fantasy, Horror, Mystery
127                       The Kid           1921         Comedy, Drama, Family
568                     Nosferatu           1922               Fantasy, Horror
194                  Sherlock Jr.           1924       Action, Comedy, Romance
193                 The Gold Rush           1925      Adventure, Comedy, Drama
..                            ...            ...                           ...
612    The Trial of the Chicago 7           2020      Drama, History, Thriller
613                          Druk           2020                 Comedy, Drama
20                Soorarai Pottru           2020                         Drama
18                       Hamilton           2020     Biography, Drama, History
205                          Soul           2020  Animation, Adventure, Comedy

[1000 rows x 3 columns]

In [64]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
(
    imdb[['Series_Title', 'Released_Year', 'Certificate', 'Gross']]
     [imdb['Released_Year'] >= 2010][imdb['IMDB_Rating'] >= 8.5]
    .sort_values('Gross', ascending=False)
)

/tmp/ipykernel_10987/3875979669.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  imdb[['Series_Title', 'Released_Year', 'Certificate', 'Gross']]

        Series_Title  Released_Year Certificate        Gross
19      Gisaengchung           2019           A   53,367,844
33             Joker           2019           A  335,451,311
8          Inception           2010          UA  292,576,195
21      Interstellar           2014          UA  188,020,017
35  The Intouchables           2011          UA   13,182,281
34          Whiplash           2014           A   13,092,000
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [65]:
# Does the sorting result look right to you? What's the problem?
# No, the sorting of gross is all over the place.

In [66]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful:
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe
imdb['Gross'] = imdb['Gross'].str.replace(',', '').astype(float)

In [67]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
(
    imdb[['Series_Title', 'Released_Year', 'Certificate', 'Gross']]
     [imdb['Released_Year'] >= 2010][imdb['IMDB_Rating'] >= 8.5]
    .sort_values('Gross', ascending=False)
)

/tmp/ipykernel_10987/1541201507.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  imdb[['Series_Title', 'Released_Year', 'Certificate', 'Gross']]

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [68]:
# Add a new column "Runtime_min" by removing the substring " min" in "Runtime"
# Set its data type as int
# Hint: https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe
Runtime_min = imdb['Runtime'].str.replace(' min', '').astype(int)
imdb['Runtime_min'] = Runtime_min
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Runtime_min
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0,142
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0,175
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0,152
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0,202
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0,96

In [69]:
# Add a new column "Age_Year" by expression: Current year - Released_Year
Age_Year = 2026 - imdb['Released_Year']
imdb['Age_Year'] = Age_Year
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Runtime_min,Age_Year
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0,142,32
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0,175,54
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0,152,18
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0,202,52
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0,96,69

In [70]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc.
Decade = (imdb['Released_Year'] // 10) * 10
imdb['Decade'] = Decade
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Runtime_min,Age_Year,Decade
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0,142,32,1990
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0,175,54,1970
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0,152,18,2000
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0,202,52,1970
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0,96,69,1950

## Part 2: Data Summarization

In [71]:
# Total "Gross" of all top 1000 movies
imdb['Gross'].agg('sum')

np.float64(56536877976.0)

In [72]:
# Average "No_of_Votes" of all movies
imdb['No_of_Votes'].agg('mean')

np.float64(273692.911)

In [73]:
# Count movies in each decade (e.g., ..., 1980, 1990, 2000, 2010, 2020)
# Sort decades by the number of movies in descending order
imdb.groupby(['Decade']).count()['Series_Title'].sort_values(ascending=False)

Decade
2010    242
2000    237
1990    151
1980     89
1970     76
1960     73
1950     56
1940     35
1930     24
1920     11
2020      6
Name: Series_Title, dtype: int64

In [74]:
# Count movies by different directors.
# Show the top 10 directors with the most movies in this list
imdb['Director'].value_counts().head(10)

Director
Alfred Hitchcock     14
Steven Spielberg     13
Hayao Miyazaki       11
Akira Kurosawa       10
Martin Scorsese      10
Woody Allen           9
Stanley Kubrick       9
Billy Wilder          9
Clint Eastwood        8
Christopher Nolan     8
Name: count, dtype: int64

In [75]:
# For each director, calculate the number of movies, average IMDB_Rating, and total gross.
# Ranked in descending order of total gross
# Show the top 10 directors with the most gross
imdb.groupby(['Director']).agg({'Series_Title': 'count', 'IMDB_Rating': 'mean', 'Gross': 'sum'}).sort_values('Gross', ascending=False).head(10)
#

                   Series_Title  IMDB_Rating         Gross
Director
Steven Spielberg             13     8.030769  2.478133e+09
Anthony Russo                 4     8.075000  2.205039e+09
Christopher Nolan             8     8.462500  1.937454e+09
James Cameron                 5     8.080000  1.748237e+09
Peter Jackson                 5     8.400000  1.597312e+09
J.J. Abrams                   3     7.833333  1.423171e+09
Brad Bird                     4     7.900000  1.099628e+09
Robert Zemeckis               5     8.120000  1.049446e+09
David Yates                   3     7.800000  9.789537e+08
Pete Docter                   4     8.125000  9.393821e+08

In [76]:
# Group movies by decade and director
# In each group (i.e., for each decade and each director),
# calculate the number of movies and average IMDB rating.
# Sort in descending order of movie count
imdb.groupby(['Decade', 'Director']).agg({'Series_Title': 'count', 'IMDB_Rating': 'mean'}).sort_values('Series_Title', ascending = False)

                             Series_Title  IMDB_Rating
Decade Director
1950   Billy Wilder                     6     8.133333
       Akira Kurosawa                   5     8.260000
2010   Denis Villeneuve                 5     7.980000
1950   Alfred Hitchcock                 5     8.220000
1980   Steven Spielberg                 5     7.980000
...                                   ...          ...
2010   Tyler Nilson                     1     7.600000
       Umesh Shukla                     1     8.100000
       Vikas Bahl                       1     8.200000
       Vikramaditya Motwane             1     8.200000
       Vishal Bhardwaj                  1     8.100000

[749 rows x 2 columns]

In [77]:
# Find the top 3 highest rated movies of each year since 2010.
# Show their released year, ranking, title, and IMDB_Rating.
# Sort them in descending order of year and ascending order of ranking
imdb[['Released_Year', 'IMDB_Rating', 'Series_Title']][imdb['Released_Year'] >= 2010].sort_values(['Released_Year', 'IMDB_Rating'], ascending=[False, True]).groupby('Released_Year').head(3)

     Released_Year  IMDB_Rating                      Series_Title
612           2020          7.8        The Trial of the Chicago 7
613           2020          7.8                              Druk
464           2020          7.9                       Dil Bechara
877           2019          7.6                       Dark Waters
879           2019          7.6  Once Upon a Time... in Hollywood
882           2019          7.6                        Just Mercy
878           2018          7.6                         Searching
891           2018          7.6                     Incredibles 2
903           2018          7.6                    A Star Is Born
880           2017          7.6                          Nelyubov
881           2017          7.6               The Florida Project
883           2017          7.6                            Gifted
892           2016          7.6                             Moana
896           2016          7.6                Hell or High Water
572           2016          7.8                        Forushande
885           2015          7.6                          Victoria
886           2015          7.6                           Mustang
890           2015          7.6                   Bridge of Spies
895           2014          7.6                          Leviafan
898           2014          7.6    Dawn of the Planet of the Apes
727           2014          7.7         What We Do in the Shadows
897           2013          7.6                         Philomena
734           2013          7.7                    La vie d'Adèle
735           2013          7.7                       Kai po che!
899           2012          7.6                         El cuerpo
901           2012          7.6                      End of Watch
736           2012          7.7       The Broken Circle Breakdown
900           2011          7.6                      Serbuan maut
907           2011          7.6                             50/50
910           2011          7.6                         Moneyball
902           2010          7.6           Kari-gurashi no Arietti
904           2010          7.6                         True Grit
905           2010          7.6                            Hævnen

In [78]:
# Find all directors whose movies appeared in at least five different decades.
# Your result should include: director, decade, and the number of movies in the decade.
imdb.groupby(['Director', 'Decade']).agg({'Series_Title': 'count'}).sort_values('Series_Title', ascending=False)

                             Series_Title
Director             Decade
Billy Wilder         1950               6
Alfred Hitchcock     1940               5
                     1950               5
Denis Villeneuve     2010               5
Akira Kurosawa       1950               5
...                                   ...
Alexander Payne      2010               1
Alex Proyas          1990               1
Alex Garland         2010               1
Alejandro Jodorowsky 1970               1
Yoshiaki Kawajiri    1990               1

[749 rows x 1 columns]

In [79]:
# Ask two questions about this dataset and write your code to answer them.
# Question 1: Average IMDB Rating for each decade.
imdb.groupby(['Decade']).agg({'IMDB_Rating': 'mean'})

        IMDB_Rating
Decade
1920       8.127273
1930       7.966667
1940       8.025714
1950       8.058929
1960       7.973973
1970       7.969737
1980       7.953933
1990       7.960927
2000       7.899578
2010       7.924380
2020       8.133333

In [80]:
# Questions 2: Top five highest grossing directors on the list.
imdb.groupby(['Director']).agg({'Gross': 'sum'}).sort_values('Gross', ascending=False).head(5)

                          Gross
Director
Steven Spielberg   2.478133e+09
Anthony Russo      2.205039e+09
Christopher Nolan  1.937454e+09
James Cameron      1.748237e+09
Peter Jackson      1.597312e+09